=== Jailson-IFRN/atividades-pos-2024/xml/xmlSchema.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:p="http://pratos.org" 
        targetNamespace = "http://pratos.org" 
        elementFormDefault="qualified">

        <element name="prato">
          <complexType>
            <sequence>
                  <element name="nome">
                    <simpleType>
                      <restriction base="string">
                        <maxLength value="100"/>
                      </restriction>
                    </simpleType>
                </element>
        
                <element name="refeição">
                  <simpleType>
                    <restriction base="string">
                      <pattern value="café|almoço|janta"/>
                    </restriction>
                  </simpleType>
              </element>
        
              <element name="ingredientes">
                <complexType>
                  <sequence>
                    <element name="ingrediente" type="string" minOccurs="1" maxOccurs="unbounded" />
                  </sequence>
                </complexType>
              </element>
        
        
              <element name="preço">
                <simpleType>
                  <restriction base="decimal">
                    <fractionDigits value="2" />
                  </restriction>
                </simpleType>
              </element>
        
              <element name="dataCadastro" type="date" /> 
            </sequence>
          </complexType>
        </element>

        





        
</schema>

=== Jailson-IFRN/atividades-pos-2024/xml/prato - exemplo.xml
<prato xmlns="http://pratos.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pratos.org xmlSchema.xsd" > 
    
    <nome>Lasanha</nome>
    <refeição>almoço</refeição>
    <ingredientes>
        <ingrediente>Macarrão</ingrediente>
        <ingrediente>Molho de tomate</ingrediente>
    </ingredientes>
    <preço>29.99</preço>
    <dataCadastro>2024-01-20</dataCadastro>

</prato>
